= Gestion de Gonflage Nitrox
:description: Systeme de gestion de gonflage et facturation O2

Ce projet est une application web legere permettant de calculer les melanges Nitrox (O2 pur + Air), de facturer les utilisateurs et de suivre la consommation globale d'oxygene.

== Fonctionnalites

* Calculateur de melange : determine la pression d'O2 a ajouter et la pression d'arrêt avant complement a l'air.
* Gestion des blocs : supporte les volumes avec decimales (ex: S40 de 5.6L).
* Facturation : enregistrement automatique dans une base de donnees MySQL.
* Suivi des paiements : interface pour marquer les factures comme payees.
* Statistiques : filtres par mois et par an pour la consommation d'O2.
* Export : generation de rapports au format CSV.

== Installation

* Création d'un mot de passe unique pour l'utilisateur de bdd :

[source,console]
----
$ sed -i "s/monsuperpass/$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 13)/g" db.php createdb.sql
----

* Construction de la base de données

[source,console]
----
$ mysql -u root -p < createdb.sql 
Enter password: 
----

* Copie des fichiers vers le serveur web : 

[source,console]
----
$ sudo mkdir /var/www/htdocs/gonflage
$ sudo install -m 644 *.php /var/www/htdocs/gonflage/
$ sudo install -m 640 db.php /var/www/htdocs/gonflage/
$ sudo install -m 644 style.css /var/www/htdocs/gonflage/
----
